name: Deploy to Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # -------------------------
      # ① テスト実行
      # -------------------------
      - name: Install dependencies
        run: npm install

      - name: Fix jest permissions
        run: chmod +x node_modules/.bin/jest

      - name: Run Tests
        run: npm test
        id: my_test_step 
        continue-on-error: true

      # -------------------------
      # ② junit.xml を S3 にアップロード
      # -------------------------
      - name: Upload test report to S3
        if: always()
        run: |
          aws s3 cp test-reports/junit.xml \
            s3://${{ secrets.S3_REPORT_BUCKET }}/test-reports/${{ github.run_id }}.xml
      
            # -------------------------
      # ⑤ テスト成功時のみ function.zip を作成
      # -------------------------
      - name: Create Lambda package
        if: steps.my_test_step.outcome == 'success'
        run: |
          zip -r function.zip index.js node_modules

      # -------------------------
      # ⑥ function.zip を S3 にアップロード
      # -------------------------
      - name: Upload Lambda package to S3
        if: steps.my_test_step.outcome == 'success'
        run: |
          aws s3 cp function.zip \
            s3://${{ secrets.S3_DEPLOY_BUCKET }}/lambda/function.zip

      # -------------------------
      # ③-1 テスト成功 → EventBridge に SUCCEEDED を送信
      # -------------------------
      - name: Send SUCCEEDED event to EventBridge
        if: steps.my_test_step.outcome == 'success'
        run: |
          aws events put-events --entries '[
            {
              "Source": "cicd.tests",
              "DetailType": "TestResult",
              "Detail": "{\"status\":\"SUCCEEDED\"}",
              "EventBusName": "default"
            }
          ]'

      # -------------------------
      # ③-2 テスト失敗 → EventBridge に FAILED を送信
      # -------------------------
      - name: Send FAILED event to EventBridge
        if: steps.my_test_step.outcome == 'failure'          
        run: |
            aws events put-events --entries '[
              {
                "Source": "custom.github.actions",
                "DetailType": "GitHub Action Build State Change",
                "Detail": "{\"build-status\": \"FAILED\", \"project-name\": \"${{ github.event.repository.name }}\", \"report-url\": \"https://s3.console.aws.amazon.com/s3/object/${{ secrets.S3_REPORT_BUCKET }}/test-reports/${{ github.run_id }}.xml?region=ap-northeast-1\"}",
                "EventBusName": "default"
              }
            ]'